var artists = ["A$AP Ferg",
"Adventure Club",
"Aeroplane",
"AFI",
"AFTA-1",
"Alesso",
"Alf Alpha",
"Aloe Blacc",
"AlunaGeorge",
"Anna Lunoe",
"Anthony Green",
"Anti Flag",
"Arcade Fire",
"Art Department",
"Austra ",
"†††",
"Banks",
"Bastille",
"Bear Hands",
"Beck",
"Benji Vaughan",
"Bicep",
"Big Gigantic",
"Blond:ish",
"Blood Orange",
"Bo Ningen",
"Bombay Bicycle Club",
"Bombino",
"Bonobo",
"Boubakiki",
"Broken Bells",
"Bryan Ferry",
"Cage the Elephant",
"Cajmere",
"Calvin Harris",
"Capital Cities",
"Caravan Palace",
"Carbon Airways",
"Carnage",
"Chance the Rapper",
"ChrisB",
"Chromeo",
"Chvrches",
"City and Colour",
"CIVX",
"Classixx",
"CO.Fee",
"Cooper Saver",
"Courtney Barnett",
"Damian Lazarus",
"DARKSIDE",
"Daughter",
"Davide Squillace",
"Deorro",
"Dillon Francis",
"Disclosure",
"Dixon",
"DJ Falcon",
"DJ Jimbo Jenkins",
"DJ Tennis",
"DJP",
"Drowners",
"Duck Sauce",
"Duke Dumont",
"Dum Dum Girls",
"Eduardo Castillo",
"Ellie Goulding",
"Empire of the Sun",
"Factory Floor",
"Fatboy Slim",
"Fishbone",
"Flatbush Zombies",
"Flight Facilities",
"Flosstradamus",
"Flume",
"Foster the People",
"Foxygen",
"Frank Turner",
"Freddy Todd",
"Future Islands",
"Gabba Gabba Heys",
"Galantis",
"Gareth Emery",
"Girl Talk",
"GOAT",
"Graveyard",
"Grouplove",
"GTA",
"Guy Gerber",
"HAIM",
"Headhunterz",
"Henry Krinkle",
"Holy Ghost!",
"Hopscotch",
"Hot Since 82",
"HunterLeggitt",
"idiot Savant",
"Isaac Tichauer",
"J Roddy Walston and the Business",
"Jabot",
"Jagwar Ma",
"James Vincent McMorrow",
"Jhene’ Aiko",
"John Beaver",
"John Newman",
"Juicewon",
"Julian Casablancas",
"Jupit3r",
"KAB",
"Kate Nash",
"Kid Cudi",
"Kidnap Kid",
"Kraddy",
"Krewella",
"Lafa Taylor",
"Lana Del Rey",
"Laura Mvula",
"Laurent Garnier",
"Lee Burridge",
"Lee Wells",
"Lesto",
"Little Dragon",
"Lorde",
"Love & Light",
"Lucent Dossier Experience",
"Lucent Dossier Experience",
"Maceo Plex",
"Machin'",
"Makj",
"Mako",
"Martin Garrix",
"MGMT",
"Michael Brun",
"Mikey Lion",
"Mitis",
"Mogwai",
"Moonboots",
"Motorhead",
"MS MR",
"Muse",
"Nas",
"Neko Case",
"Netsky",
"Neutral Milk Hotel",
"Nicolas Jaar",
"Nicole Moudaber",
"Nina Kraviz",
"Odesza",
"Opiuo",
"OutKast",
"Patricio",
"Perseus",
"Pet Shop Boys",
"Pharrell Williams",
"Pixies",
"Poolside",
"Preservation Hall Jazz Band",
"Queens of the Stone Age",
"Ratking",
"Ravell",
"Ricoshei",
"RL Grime",
"Rudimental",
"Ruff Hauser",
"Saints of Valory",
"Sander Kleinenberg",
"Scuba",
"Shlohmo",
"Showtek",
"Skrillex",
"Sleigh Bells",
"Solange",
"Solomun",
"STRFKR",
"Superchunk",
"Surfer Blood",
"Sweater Beats",
"Syd Arthur",
"Temples",
"The 1975",
"The Afghan Whigs",
"The Bots",
"The Cult",
"The Dismemberment Plan",
"The Glitch Mob",
"The Head and the Heart",
"The Internet",
"The Jon Spencer Blues Explosion",
"The Knife",
"The Magician",
"The Martinez Brothers",
"The Naked and Famous",
"The Preatures",
"The Replacements",
"The Toy Dolls",
"Thugfucker",
"Tiga",
"Title Fight",
"TJR",
"Tom Odell",
"Trombone Shorty & Orleans Avenue",
"Ty Segall",
"Unlocking the Truth",
"UZ",
"Warpaint",
"Washed Out",
"Waxahatchee",
"White Lies",
"Woodkid",
"WoodysProduce",
"Wye Oak",
"Young and Sick",
"Zedd",
"Zoè",
"ZZ Ward"];
var handles = ["ASAPferg",
    "AdventureDub",
    "vitoaeroplane",
    "afi",
    "Alesso",
    "alfalpha",
    "aloeblacc",
    "alunageorge",
    "ANNALUNOE",
    "anthonygreen",
    "anti_flag",
    "arcadefire",
    "ARTDEPTMUSIC",
    "austratalks",
    "crossesmusic",
    "hernameisbanks",
    "bastilledan",
    "bearhandsband",
    "beck",
    "feelmybicep",
    "biggigantic",
    "blond_ish",
    "devhynes",
    "boningenuk",
    "BombayBicycle",
    "BombinoOfficial",
    "sibonobo",
    "broken_bells",
    "bryanferry",
    "cagetheelephant",
    "Cajmere_",
    "calvinharris",
    "capitalcities",
    "caravan_palace",
    "carbonairways",
    "djcarnage",
    "chancetherapper",
    "chromeo",
    "chvrches",
    "cityandcolour",
    "civxmusic",
    "Classixx",
    "Co_fee",
    "coopersaver",
    "courtneymelba",
    "damianlazarus",
    "DarksideUSA",
    "ohdaughter",
    "DavideSquillace",
    "deorro",
    "dillonfrancis",
    "disclosure",
    "innrvsns",
    "IamDJFalcon",
    "djjimbojenkins",
    "dj_tennis",
    "DROWNERSBAND",
    "DuckSauceNYC",
    "DukeDumont",
    "dumdumgirls",
    "educastillo",
    "elliegoulding",
    "EmpireOfTheSun",
    "factoryfloor",
    "FatboySlim",
    "fishbonesoldier",
    "flatbushzombies",
    "flightfac",
    "flosstradamus",
    "flumemusic",
    "fosterthepeople",
    "foxygentheband",
    "FrankTurner",
    "freddytoddmusic",
    "futureislands",
    "LetsGo_RAMONES",
    "wearegalantis",
    "garethemery",
    "girltalk",
    "graveyard",
    "grouplove",
    "wearegta",
    "guygerber",
    "haimtheband/",
    "djheadhunterz",
    "HenryKrinkle_",
    "HolyGhostNYC",
    "hotsince82",
    "hunterleggitt",
    "ISAACTICHAUER",
    "JRoddyBusiness",
    "jagwarma",
    "jamesvmcmorrow",
    "jheneaiko",
    "om/djjohnbeaver",
    "JohnNewmanMusic",
    "juicewon",
    "Casablancas_J",
    "Jupit3rMusic",
    "katenash",
    "ducidni",
    "kidnapkid",
    "kraddyodaddy",
    "Krewella",
    "lafataylor",
    "lanadelrey",
    "lauramvula",
    "laurentgarnier",
    "leebu",
    "eewellsmusic",
    "djgabereal",
    "LittleDragon",
    "lordemusic",
    "LoveNLightMusic",
    "LucentDossier",
    "LucentDossier",
    "MaceoPlex",
    "DJMAKJ",
    "wearemako",
    "martingarrix",
    "whoisMGMT",
    "michaelbrun",
    "MrMikeyLion",
    "MitisOfficial",
    "mogwaiband",
    "myMotorhead",
    "msmrsounds",
    "muse",
    "nas",
    "NekoCase",
    "netskymusic",
    "NeutralMilkFans",
    "nicolemoudaber",
    "NinaKraviz",
    "OPIUO",
    "petshopboys",
    "pharrell",
    "PIXIES",
    "poolside",
    "preshallband",
    "qotsa",
    "RATKING",
    "RavellsTweets",
    "ricosheimusic",
    "rlgrime",
    "rudimentaluk",
    "RuffHauser",
    "SaintsofValory",
    "kleinenberg",
    "ScubaOfficial",
    "shlohmo",
    "showtekmusic",
    "skrillex",
    "sleighbells",
    "solangeknowles",
    "SolomunMusic",
    "starfucker",
    "superchunk",
    "surferblood",
    "sweaterbeats",
    "sydarthurband",
    "templesofficial",
    "the1975",
    "theafghanwhigs",
    "thebotsband",
    "officialcult",
    "thedplan",
    "theglitchmob",
    "headandtheheart",
    "intanetz",
    "jsbx_1",
    "theknifenews",
    "themagicianclub",
    "themartinezbros",
    "tnaf/",
    "ThePreatures",
    "TheReplacements",
    "ciaotiga",
    "titlefight",
    "TJR",
    "tompeterodell",
    "tromboneshorty",
    "tysegall",
    "UnlocktheTruth3",
    "BallTrapMusic",
    "_warpaint",
    "ernestgreene",
    "k_crutchfield",
    "whiteliesmusic",
    "Woodkid",
    "WoodysProduce",
    "wyeoak",
    "Zedd",
    "zoetheband",
    "ZZWard"];
